"""
Configuration complète pour le générateur de blog sur la psychologie humaine.
Contient toutes les catégories, sujets, contextes, profils, angles, prénoms et tranches d'âge.
"""

CATEGORIES = {
    "cat1_pensees": {
        "name": "Reprendre le contrôle de ses pensées",
        "slug": "reprendre-le-controle-de-ses-pensees",
        "sujets": [
            # BIAIS COGNITIFS
            "biais de confirmation",
            "biais d'ancrage",
            "biais de disponibilité",
            "effet Dunning-Kruger",
            "biais de négativité",
            "biais d'optimisme",
            "biais de statu quo",
            "effet de halo",
            "biais de conformité",
            "biais rétrospectif",
            "biais d'attribution fondamentale",
            "biais de projection",
            "biais de cadrage",
            "effet de simple exposition",
            "biais d'autorité",
            "biais de représentativité",
            "biais de survivant",
            "effet Barnum/Forer",
            "biais d'engagement/escalade d'engagement",
            "effet de dotation",
            "biais de normalité",
            "biais du point aveugle",
            "effet Zeigarnik",
            "biais de faux consensus",
            "biais de l'angle mort",
            "effet de récence",
            "effet de primauté",
            "biais du coût irrécupérable",
            "biais de l'autruche",
            "effet spotlight",
            "biais de complaisance",
            "illusion de contrôle",
            "illusion de transparence",
            "effet de leurre",
            "biais de distinction",
            "biais de groupe",
            "pensée de groupe",
            "effet bandwagon",
            "biais d'omission",
            "biais d'action",
            "biais de proportionnalité",
            "heuristique d'affect",
            "biais de croyance",
            "effet de vérité illusoire",
            "biais de la tache aveugle",
            "biais du monde juste",
            "biais de la malédiction du savoir",
            "effet IKEA",
            "biais de l'unité",
            "peak-end rule",
            "biais de cadrage positif vs négatif",
            "biais de choix favorable",
            "biais de congruence",
            "effet de contexte",
            "biais du risque zéro",
            "biais de déclin",
            "négligence de la taille de l'échantillon",
            "corrélation illusoire",
            "effet de contraste",
            "biais de la fenêtre d'Overton",
            # DISTORSIONS COGNITIVES
            "pensée tout-ou-rien (pensée dichotomique)",
            "surgénéralisation",
            "filtre mental (abstraction sélective)",
            "disqualification du positif",
            "lecture de pensée",
            "divination (prédire l'avenir négativement)",
            "catastrophisation (dramatisation)",
            "minimisation",
            "raisonnement émotionnel",
            "les \"je dois/il faut\" (obligations rigides)",
            "étiquetage",
            "personnalisation",
            "blâme externalisé",
            "comparaison injuste",
            "orientation vers le regret",
            "pensée du \"et si\" (what-if thinking)",
            # TYPES DE PENSÉES
            "rumination mentale",
            "pensées intrusives",
            "pensées automatiques négatives",
            "inquiétude chronique",
            "overthinking (surpensée)",
            "auto-critique interne",
            "dialogue intérieur négatif",
            "catastrophisme",
            "anticipation anxieuse",
            "pensée magique",
            "pensées obsédantes",
            # TECHNIQUES CAT1
            "restructuration cognitive (TCC)",
            "défusion cognitive (ACT)",
            "recadrage cognitif",
            "pleine conscience des pensées",
            "questionnement socratique",
            "technique STOP",
            "méthode ABCDE d'Ellis",
            "méditation de l'observateur",
            "journaling de pensées",
            "technique des 3 colonnes de Beck",
            "mise à distance cognitive",
            "expérience comportementale",
            "flèche descendante",
            "technique du tribunal",
            "double standard",
            "décatastrophisation",
            "recherche de preuves",
        ],
    },
    "cat2_emotions": {
        "name": "Comprendre et maîtriser ses émotions",
        "slug": "comprendre-et-maitriser-ses-emotions",
        "sujets": [
            # ÉMOTIONS
            "colère",
            "tristesse",
            "peur",
            "joie",
            "dégoût",
            "surprise",
            "honte",
            "culpabilité",
            "jalousie",
            "envie",
            "frustration",
            "anxiété",
            "ennui",
            "solitude",
            "nostalgie",
            "fierté",
            "amour",
            "gratitude",
            "espoir",
            "mépris",
            "embarras",
            "mélancolie",
            "euphorie",
            "amertume",
            "résignation",
            "enthousiasme",
            "compassion",
            "indifférence",
            "rage",
            "irritabilité",
            "agacement",
            "impatience",
            "inquiétude",
            "terreur",
            "panique",
            "appréhension",
            "déception",
            "regret",
            "remords",
            "humiliation",
            "vulnérabilité",
            "impuissance",
            "désespoir",
            "accablement",
            "sentiment d'injustice",
            "trahison",
            "abandon émotionnel",
            "rejet",
            "inadéquation",
            "vide intérieur",
            "apathie",
            "ambivalence émotionnelle",
            "confusion émotionnelle",
            "sentiment d'imposture",
            "satisfaction",
            "sérénité",
            "tendresse",
            "émerveillement",
            "excitation",
            "soulagement",
            "plénitude",
            "contentement",
            # CONCEPTS ÉMOTIONNELS
            "roue de Plutchik",
            "émotions primaires vs secondaires",
            "émotions mixtes",
            "intelligence émotionnelle (Goleman - 5 composantes)",
            "quotient émotionnel",
            "théorie de James-Lange",
            "théorie de Schachter-Singer",
            "théorie de Lazarus",
            "constructionnisme émotionnel (Lisa Feldman Barrett)",
            "granularité émotionnelle",
            "régulation émotionnelle",
            "suppression émotionnelle vs réévaluation cognitive",
            "fenêtre de tolérance (Dan Siegel)",
            "hyper-activation vs hypo-activation",
            "résilience émotionnelle",
            "alexithymie",
            "hyperréactivité émotionnelle",
            "contagion émotionnelle",
            "empathie cognitive vs affective",
            "fatigue de compassion",
            "dette émotionnelle",
            "charge mentale émotionnelle",
            "mémoire émotionnelle",
            "flashbacks émotionnels",
            "triggers/déclencheurs émotionnels",
            # TECHNIQUES CAT2
            "cohérence cardiaque",
            "ancrage sensoriel (grounding 5-4-3-2-1)",
            "journal émotionnel",
            "technique RAIN (Reconnaître-Accepter-Investiguer-Ne pas s'identifier)",
            "roue des émotions (outil pratique)",
            "body scan",
            "auto-compassion (Kristin Neff)",
            "respiration en boîte (box breathing)",
            "respiration 4-7-8",
            "technique du papillon (EMDR simplifié)",
            "visualisation du lieu sûr",
            "l'accueil émotionnel en 4 étapes",
            "la météo intérieure",
            "écriture expressive (Pennebaker)",
            "la lettre non envoyée",
            "la technique du zoom arrière",
            "le scan corporel des émotions",
            "la méthode TIPI (Luc Nicon)",
            "la pleine conscience des émotions",
        ],
    },
    "cat3_schemas": {
        "name": "Sortir de ses schémas répétitifs",
        "slug": "sortir-de-ses-schemas-repetitifs",
        "sujets": [
            # 18 SCHÉMAS DE YOUNG
            "abandon/instabilité",
            "méfiance/abus",
            "manque affectif",
            "imperfection/honte",
            "isolement social/aliénation",
            "dépendance/incompétence",
            "vulnérabilité au danger",
            "fusion/personnalité atrophiée",
            "échec",
            "droits personnels excessifs/grandiosité",
            "contrôle de soi insuffisant",
            "assujettissement",
            "abnégation/sacrifice de soi",
            "recherche d'approbation/reconnaissance",
            "négativité/pessimisme",
            "surcontrôle émotionnel/inhibition",
            "exigences élevées/critique excessive",
            "punition",
            # STYLES D'ATTACHEMENT
            "attachement sécure (caractéristiques, comment le développer)",
            "attachement anxieux-préoccupé (hyperactivation du système)",
            "attachement évitant-dédaigneux (désactivation du système)",
            "attachement désorganisé/craintif (oscillation)",
            "l'attachement dans le couple",
            "l'attachement et la parentalité",
            "la théorie de Bowlby",
            "la situation étrange de Mary Ainsworth",
            "le modèle interne opérant",
            "la figure d'attachement",
            "le système d'attachement à l'âge adulte",
            "la dépendance affective vs l'attachement anxieux",
            # MÉCANISMES DE DÉFENSE
            "déni",
            "projection",
            "rationalisation",
            "régression",
            "sublimation",
            "déplacement",
            "formation réactionnelle",
            "intellectualisation",
            "refoulement",
            "clivage",
            "identification projective",
            "idéalisation/dévaluation",
            "humour comme défense",
            "isolation de l'affect",
            "annulation rétroactive",
            "acting out (passage à l'acte)",
            "somatisation",
            "dissociation",
            "fantasme",
            "compensation",
            "évitement",
            "contrôle omnipotent",
            # CONCEPTS CAT3
            "compulsion de répétition (Freud)",
            "enfant intérieur",
            "les 5 blessures de l'âme (Lise Bourbeau : rejet, abandon, humiliation, trahison, injustice)",
            "les 5 masques correspondants (fuyant, dépendant, masochiste, contrôlant, rigide)",
            "loyautés invisibles (Boszormenyi-Nagy)",
            "transmissions transgénérationnelles",
            "croyances limitantes",
            "croyances fondamentales",
            "prophéties autoréalisatrices",
            "le scénario de vie (Analyse Transactionnelle - Eric Berne)",
            "les drivers/messages contraignants (sois parfait, fais plaisir, sois fort, dépêche-toi, fais des efforts)",
            "les jeux psychologiques (triangle de Karpman : persécuteur, victime, sauveur)",
            "les états du Moi (Parent, Adulte, Enfant)",
            "les positions de vie (+/+, +/-, -/+, -/-)",
            "le faux self (Winnicott)",
            "le syndrome de l'imposteur",
            "le narcissisme sain vs pathologique",
            "la blessure narcissique",
            "les relations toxiques (patterns)",
            "la codépendance",
            "le gaslighting et la manipulation psychologique",
            "le cycle de l'abus (tension, explosion, lune de miel)",
            "le trauma bonding (attachement traumatique)",
            "le stress post-traumatique complexe (C-PTSD)",
            "la parentification",
            "l'adultification",
            "le syndrome de Stockholm du quotidien",
            # TECHNIQUES CAT3
            "reparentage (schéma-thérapie)",
            "technique de la chaise vide (Gestalt)",
            "ligne de vie (exercice)",
            "génogramme simplifié",
            "journal des patterns/schémas",
            "technique du recul temporel",
            "la lettre à son enfant intérieur",
            "le dialogue avec ses parts",
            "le travail sur les modes de Young (enfant vulnérable, parent punitif, adulte sain)",
            "la technique de l'avocat de la défense (contre le parent critique interne)",
            "la visualisation de reparentage",
            "les flashcards de schémas",
            "le contrat avec soi-même",
            "la technique du film de sa vie",
            "le défi comportemental progressif",
            "l'identification des déclencheurs",
            "la roue des schémas (exercice)",
            "la technique des alternatives",
            "le test des schémas simplifié",
        ],
    },
}

CONTEXTES = [
    "au travail",
    "en couple",
    "en famille",
    "avec ses parents",
    "avec ses enfants",
    "en amitié",
    "à l'école ou aux études",
    "lors d'un entretien d'embauche",
    "en tant que manager",
    "face à l'argent et aux finances",
    "sur les réseaux sociaux",
    "en situation de conflit",
    "après une rupture amoureuse",
    "lors d'un deuil",
    "en période de reconversion professionnelle",
    "face à la maladie",
    "en société et dans les interactions sociales",
    "seul(e) face à soi-même",
    "face à une décision importante",
    "en situation de compétition",
    "après un échec",
    "après un succès",
    "en voyage ou en expatriation",
    "face à l'autorité",
    "dans l'intimité et la sexualité",
    "face au vieillissement",
    "en colocation",
    "lors d'un déménagement",
    "en période de fêtes de famille",
    "face à la solitude",
]

PROFILS = [
    "hypersensible",
    "perfectionniste",
    "anxieux(se)",
    "introverti(e)",
    "extraverti(e)",
    "haut potentiel intellectuel (HPI)",
    "dépendant(e) affectif(ve)",
    "évitant(e)",
    "procrastinateur(trice)",
    "en burn-out",
    "empathe",
    "timide",
    "people pleaser (celui/celle qui veut plaire à tout le monde)",
    "hyperactif(ve) / TDAH",
    "contrôlant(e)",
    "hypocondriaque",
    "ancien(ne) enfant parentifié(e)",
    "survivant(e) de relation toxique",
    "personne adoptée",
    "enfant unique / aîné(e) / cadet(te) / benjamin(e)",
]

ANGLES = [
    "comprendre ce que c'est (article explicatif)",
    "les signes que vous êtes concerné(e)",
    "les causes profondes (pourquoi ça existe)",
    "les conséquences sur votre vie quotidienne",
    "comment s'en libérer concrètement",
    "3 techniques/exercices pratiques",
    "les erreurs que tout le monde fait",
    "les idées reçues et mythes à déconstruire",
    "le lien avec l'enfance et l'éducation",
    "ce que dit la science (études et recherches)",
    "comment ça se manifeste sans qu'on s'en rende compte",
    "la différence entre [concept A] et [concept B]",
    "pourquoi ça empire avec le temps si on ne fait rien",
    "comment aider quelqu'un qui vit ça",
    "le témoignage (raconter l'histoire d'un personnage qui s'en sort)",
]

# Les 20 personnages récurrents du blog (identités fixes et cohérentes)
# Le détail complet de chaque personnage est dans personnages.json
PERSONNAGES_PRENOMS = [
    "Sophie",     # 28 ans, développeuse web, perfectionniste, introvertie
    "Thomas",     # 34 ans, enseignant, people pleaser, empathique
    "Camille",    # 42 ans, infirmière, hypersensible, anxieuse, mère de 2
    "Lucas",      # 24 ans, étudiant école de commerce, insécure, compétitif
    "Nadia",      # 38 ans, directrice marketing, contrôlante, divorcée
    "Adrien",     # 31 ans, graphiste freelance, émotif, post-rupture
    "Margot",     # 52 ans, en reconversion, ancienne cadre, quête de sens
    "Youssef",    # 29 ans, ingénieur, introverti, intellectualise ses émotions
    "Isabelle",   # 47 ans, psychologue scolaire, ex-enfant parentifiée
    "Patrick",    # 56 ans, chef d'équipe BTP, stoïque, émotions refoulées
    "Léa",        # 23 ans, étudiante psycho, idéaliste, codépendante
    "Karim",      # 40 ans, entrepreneur restauration, ambitieux, père de 3
    "Monique",    # 62 ans, retraitée prof de français, veuve, nostalgique
    "Hugo",       # 27 ans, musicien, émotif, dépendant affectif
    "Priya",      # 33 ans, médecin, évitante, surinvestie au travail
    "Stéphane",   # 45 ans, commercial, anxieux social masqué, compétitif
    "Djamila",    # 36 ans, travailleuse sociale, survivante relation toxique
    "Fabien",     # 50 ans, cadre RH, divorcé, burn-out latent
    "Mei",        # 22 ans, étudiante en art, timide, anxiété sociale
    "Bernard",    # 58 ans, artisan ébéniste, veuf, taiseux
]

# Conservé pour compatibilité mais le système utilise maintenant PERSONNAGES_PRENOMS
PRENOMS = PERSONNAGES_PRENOMS

TRANCHES_AGE = [
    "jeune adulte (20-25 ans)",
    "adulte en construction (26-35 ans)",
    "adulte en pleine vie active (36-45 ans)",
    "adulte en bilan de mi-vie (46-55 ans)",
    "senior en quête de sens (56-70 ans)",
]
